module ApplicationHelper

  def display_base_errors resource
    return '' if (resource.errors.empty?) or (resource.errors[:base].empty?)
    messages = resource.errors[:base].map { |msg| content_tag(:p, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-block">
      <button type="button" class="close" data-dismiss="alert">&#215;</button>
      #{messages}
    </div>
    HTML
    html.html_safe
  end

  def get_champion_name id
    case id
    when 266 then "Aatrox"
    when 103 then "Ahri"
    when 84 then "Akali"
    when 12 then "Alistar"
    when 32 then "Amumu"
    when 34 then "Anivia"
    when 1 then "Annie"
    when 22 then "Ashe"
    when 53 then "Blitzcrank"
    when 63 then "Brand"
    when 51 then "Caitlyn"
    when 69 then "Cassiopeia"
    when 31 then "Chogath"
    when 42 then "Corki"
    when 122 then "Darius"
    when 131 then "Diana"
    when 119 then "Draven"
    when 36 then "DrMundo"
    when 60 then "Elise"
    when 28 then "Evelynn"
    when 81 then "Ezreal"
    when 9 then "FiddleSticks"
    when 114 then "Fiora"
    when 105 then "Fizz"
    when 3 then "Galio"
    when 41 then "Gangplank"
    when 86 then "Garen"
    when 79 then "Gragas"
    when 104 then "Graves"
    when 120 then "Hecarim"
    when 74 then "Heimerdinger"
    when 39 then "Irelia"
    when 40 then "Janna"
    when 59 then "JarvanIV"
    when 24 then "Jax"
    when 126 then "Jayce"
    when 222 then "Jinx"
    when 43 then "Karma"
    when 30 then "Karthus"
    when 38 then "Kassadin"
    when 55 then "Katarina"
    when 10 then "Kayle"
    when 85 then "Kennen"
    when 121 then "Khazix"
    when 96 then "KogMaw"
    when 7 then "Leblanc"
    when 64 then "LeeSin"
    when 89 then "Leona"
    when 127 then "Lissandra"
    when 236 then "Lucian"
    when 117 then "Lulu"
    when 99 then "Lux"
    when 54 then "Malphite"
    when 90 then "Malzahar"
    when 57 then "Maokai"
    when 11 then "MasterYi"
    when 21 then "MissFortune"
    when 62 then "MonkeyKing"
    when 82 then "Mordekaiser"
    when 25 then "Morgana"
    when 267 then "Nami"
    when 75 then "Nasus"
    when 111 then "Nautilus"
    when 76 then "Nidalee"
    when 56 then "Nocturne"
    when 20 then "Nunu"
    when 2 then "Olaf"
    when 61 then "Orianna"
    when 80 then "Pantheon"
    when 78 then "Poppy"
    when 133 then "Quinn"
    when 33 then "Rammus"
    when 58 then "Renekton"
    when 107 then "Rengar"
    when 92 then "Riven"
    when 68 then "Rumble"
    when 13 then "Ryze"
    when 113 then "Sejuani"
    when 35 then "Shaco"
    when 98 then "Shen"
    when 102 then "Shyvana"
    when 27 then "Singed"
    when 14 then "Sion"
    when 15 then "Sivir"
    when 72 then "Skarner"
    when 37 then "Sona"
    when 16 then "Soraka"
    when 50 then "Swain"
    when 134 then "Syndra"
    when 91 then "Talon"
    when 44 then "Taric"
    when 17 then "Teemo"
    when 412 then "Thresh"
    when 18 then "Tristana"
    when 48 then "Trundle"
    when 23 then "Tryndamere"
    when 4 then "TwistedFate"
    when 29 then "Twitch"
    when 77 then "Udyr"
    when 6 then "Urgot"
    when 110 then "Varus"
    when 67 then "Vayne"
    when 45 then "Veigar"
    when 254 then "Vi"
    when 112 then "Viktor"
    when 8 then "Vladimir"
    when 106 then "Volibear"
    when 19 then "Warwick"
    when 101 then "Xerath"
    when 5 then "XinZhao"
    when 83 then "Yorick"
    when 154 then "Zac"
    when 238 then "Zed"
    when 115 then "Ziggs"
    when 26 then "Zilean"
    when 143 then "Zyra"
    end
  end

  def get_summoner_spell_name id
    case id
    when 21 then "Barrier"
    when 16 then "BattleCry"
    when 1 then "Boost"
    when 2 then "Clairvoyance"
    when 14 then "Dot"
    when 3 then "Exhaust"
    when 4 then "Flash"
    when 5 then "Fortify"
    when 6 then "Haste"
    when 7 then "Heal"
    when 13 then "Mana"
    when 17 then "OdinGarrison"
    when 20 then "PromoteSR"
    when 9 then "Rally"
    when 10 then "Revive"
    when 11 then "Smite"
    when 12 then "Teleport"
    end
  end

end
