module ApplicationHelper

  def display_base_errors resource
    return '' if (resource.errors.empty?) or (resource.errors[:base].empty?)
    messages = resource.errors[:base].map { |msg| content_tag(:p, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-block">
      <button type="button" class="close" data-dismiss="alert">&#215;</button>
      #{messages}
    </div>
    HTML
    html.html_safe
  end

  def get_champion_name id
    case id
    when 266 then "Aatrox"
    when 103 then "Ahri"
    when 84 then "Akali"
    when 12 then "Alistar"
    when 32 then "Amumu"
    when 34 then "Anivia"
    when 1 then "Annie"
    when 22 then "Ashe"
    when 53 then "Blitzcrank"
    when 63 then "Brand"
    when 51 then "Caitlyn"
    when 69 then "Cassiopeia"
    when 31 then "Chogath"
    when 42 then "Corki"
    when 122 then "Darius"
    when 131 then "Diana"
    when 119 then "Draven"
    when 36 then "DrMundo"
    when 60 then "Elise"
    when 28 then "Evelynn"
    when 81 then "Ezreal"
    when 9 then "Fiddlesticks"
    when 114 then "Fiora"
    when 105 then "Fizz"
    when 3 then "Galio"
    when 41 then "Gangplank"
    when 86 then "Garen"
    when 79 then "Gragas"
    when 104 then "Graves"
    when 120 then "Hecarim"
    when 74 then "Heimerdinger"
    when 39 then "Irelia"
    when 40 then "Janna"
    when 59 then "JarvanIV"
    when 24 then "Jax"
    when 126 then "Jayce"
    when 222 then "Jinx"
    when 43 then "Karma"
    when 30 then "Karthus"
    when 38 then "Kassadin"
    when 55 then "Katarina"
    when 10 then "Kayle"
    when 85 then "Kennen"
    when 121 then "Khazix"
    when 96 then "KogMaw"
    when 7 then "Leblanc"
    when 64 then "LeeSin"
    when 89 then "Leona"
    when 127 then "Lissandra"
    when 236 then "Lucian"
    when 117 then "Lulu"
    when 99 then "Lux"
    when 54 then "Malphite"
    when 90 then "Malzahar"
    when 57 then "Maokai"
    when 11 then "MasterYi"
    when 21 then "MissFortune"
    when 62 then "MonkeyKing"
    when 82 then "Mordekaiser"
    when 25 then "Morgana"
    when 267 then "Nami"
    when 75 then "Nasus"
    when 111 then "Nautilus"
    when 76 then "Nidalee"
    when 56 then "Nocturne"
    when 20 then "Nunu"
    when 2 then "Olaf"
    when 61 then "Orianna"
    when 80 then "Pantheon"
    when 78 then "Poppy"
    when 133 then "Quinn"
    when 33 then "Rammus"
    when 58 then "Renekton"
    when 107 then "Rengar"
    when 92 then "Riven"
    when 68 then "Rumble"
    when 13 then "Ryze"
    when 113 then "Sejuani"
    when 35 then "Shaco"
    when 98 then "Shen"
    when 102 then "Shyvana"
    when 27 then "Singed"
    when 14 then "Sion"
    when 15 then "Sivir"
    when 72 then "Skarner"
    when 37 then "Sona"
    when 16 then "Soraka"
    when 50 then "Swain"
    when 134 then "Syndra"
    when 91 then "Talon"
    when 44 then "Taric"
    when 17 then "Teemo"
    when 412 then "Thresh"
    when 18 then "Tristana"
    when 48 then "Trundle"
    when 23 then "Tryndamere"
    when 4 then "TwistedFate"
    when 29 then "Twitch"
    when 77 then "Udyr"
    when 6 then "Urgot"
    when 110 then "Varus"
    when 67 then "Vayne"
    when 45 then "Veigar"
    when 254 then "Vi"
    when 112 then "Viktor"
    when 8 then "Vladimir"
    when 106 then "Volibear"
    when 19 then "Warwick"
    when 101 then "Xerath"
    when 5 then "XinZhao"
    when 83 then "Yorick"
    when 154 then "Zac"
    when 238 then "Zed"
    when 115 then "Ziggs"
    when 26 then "Zilean"
    when 143 then "Zyra"
    end
  end

  def get_summoner_spell_name id
    case id
    when 21 then "Barrier"
    when 16 then "BattleCry"
    when 1 then "Boost"
    when 2 then "Clairvoyance"
    when 14 then "Ignite"
    when 3 then "Exhaust"
    when 4 then "Flash"
    when 5 then "Fortify"
    when 6 then "Ghost"
    when 7 then "Heal"
    when 13 then "Mana"
    when 17 then "OdinGarrison"
    when 20 then "PromoteSR"
    when 9 then "Rally"
    when 10 then "Revive"
    when 11 then "Smite"
    when 12 then "Teleport"
    end
  end

  def get_item_name id
    case id
    when 1001 then "Boots of Speed"
    when 1004 then "Faerie Charm"
    when 1006 then "Rejuvenation Bead"
    when 1011 then "Giant's Belt"
    when 1018 then "Cloak of Agility"
    when 1026 then "Blasting Wand"
    when 1027 then "Sapphire Crystal"
    when 1028 then "Ruby Crystal"
    when 1029 then "Cloth Armor"
    when 1031 then "Chain Vest"
    when 1033 then "Null-Magic Mantle"
    when 1036 then "Long Sword"
    when 1037 then "Pickaxe"
    when 1038 then "B. F. Sword"
    when 1039 then "Hunter's Machete"
    when 1042 then "Dagger"
    when 1043 then "Recurve Bow"
    when 1051 then "Brawler's Gloves"
    when 1052 then "Amplifying Tome"
    when 1053 then "Vampiric Scepter"
    when 1054 then "Doran's Shield"
    when 1055 then "Doran's Blade"
    when 1056 then "Doran's Ring"
    when 1057 then "Negatron Cloak"
    when 1058 then "Needlessly Large Rod"
    when 1062 then "Prospector's Blade"
    when 1063 then "Prospector's Ring"
    when 1080 then "Spirit Stone"
    when 2003 then "Health Potion"
    when 2004 then "Mana Potion"
    when 2009 then "Total Biscuit of Rejuvenation"
    when 2010 then "Total Biscuit of Rejuvenation"
    when 2037 then "Elixir of Fortitude"
    when 2039 then "Elixir of Brilliance"
    when 2040 then "Ichor of Rage"
    when 2041 then "Crystalline Flask"
    when 2043 then "Vision Ward"
    when 2044 then "Stealth Ward"
    when 2045 then "Ruby Sightstone"
    when 2047 then "Oracle's Extract"
    when 2048 then "Ichor of Illumination"
    when 2049 then "Sightstone"
    when 2050 then "Explorer's Ward"
    when 2051 then "Guardian's Horn"
    when 2052 then "Poro-Snax"
    when 3001 then "Abyssal Scepter"
    when 3003 then "Archangel's Staff"
    when 3004 then "Manamune"
    when 3005 then "Atma's Impaler"
    when 3006 then "Berserker's Greaves"
    when 3007 then "Archangel's Staff (Crystal Scar)"
    when 3008 then "Manamune (Crystal Scar)"
    when 3009 then "Boots of Swiftness"
    when 3010 then "Catalyst the Protector"
    when 3020 then "Sorcerer's Shoes"
    when 3022 then "Frozen Mallet"
    when 3023 then "Twin Shadows"
    when 3024 then "Glacial Shroud"
    when 3025 then "Iceborn Gauntlet"
    when 3026 then "Guardian Angel"
    when 3027 then "Rod of Ages"
    when 3028 then "Chalice of Harmony"
    when 3029 then "Rod of Ages (Crystal Scar)"
    when 3031 then "Infinity Edge"
    when 3035 then "Last Whisper"
    when 3040 then "Seraph's Embrace"
    when 3041 then "Mejai's Soulstealer"
    when 3042 then "Muramana"
    when 3043 then "Muramana"
    when 3044 then "Phage"
    when 3046 then "Phantom Dancer"
    when 3047 then "Ninja Tabi"
    when 3048 then "Seraph's Embrace"
    when 3050 then "Zeke's Herald"
    when 3056 then "Ohmwrecker"
    when 3057 then "Sheen"
    when 3060 then "Banner of Command"
    when 3065 then "Spirit Visage"
    when 3067 then "Kindlegem"
    when 3068 then "Sunfire Cape"
    when 3069 then "Talisman of Ascension"
    when 3070 then "Tear of the Goddess"
    when 3071 then "The Black Cleaver"
    when 3072 then "The Bloodthirster"
    when 3073 then "Tear of the Goddess (Crystal Scar)"
    when 3074 then "Ravenous Hydra (Melee Only)"
    when 3075 then "Thornmail"
    when 3077 then "Tiamat (Melee Only)"
    when 3078 then "Trinity Force"
    when 3082 then "Warden's Mail"
    when 3083 then "Warmog's Armor"
    when 3084 then "Overlord's Bloodmail"
    when 3085 then "Runaan's Hurricane (Ranged Only)"
    when 3086 then "Zeal"
    when 3087 then "Statikk Shiv"
    when 3089 then "Rabadon's Deathcap"
    when 3090 then "Wooglet's Witchcap"
    when 3091 then "Wit's End"
    when 3092 then "Frost Queen's Claim"
    when 3093 then "Avarice Blade"
    when 3096 then "Nomad's Medallion"
    when 3097 then "Emblem of Valor"
    when 3098 then "Frostfang"
    when 3100 then "Lich Bane"
    when 3101 then "Stinger"
    when 3102 then "Banshee's Veil"
    when 3105 then "Aegis of the Legion"
    when 3106 then "Madred's Razors"
    when 3108 then "Fiendish Codex"
    when 3110 then "Frozen Heart"
    when 3111 then "Mercury's Treads"
    when 3112 then "Orb of Winter"
    when 3115 then "Nashor's Tooth"
    when 3116 then "Rylai's Crystal Scepter"
    when 3117 then "Boots of Mobility"
    when 3123 then "Executioner's Calling"
    when 3124 then "Guinsoo's Rageblade"
    when 3128 then "Deathfire Grasp"
    when 3131 then "Sword of the Divine"
    when 3134 then "The Brutalizer"
    when 3135 then "Void Staff"
    when 3136 then "Haunting Guise"
    when 3139 then "Mercurial Scimitar"
    when 3140 then "Quicksilver Sash"
    when 3141 then "Sword of the Occult"
    when 3142 then "Youmuu's Ghostblade"
    when 3143 then "Randuin's Omen"
    when 3144 then "Bilgewater Cutlass"
    when 3145 then "Hextech Revolver"
    when 3146 then "Hextech Gunblade"
    when 3151 then "Liandry's Torment"
    when 3152 then "Will of the Ancients"
    when 3153 then "Blade of the Ruined King"
    when 3154 then "Wriggle's Lantern"
    when 3155 then "Hexdrinker"
    when 3156 then "Maw of Malmortius"
    when 3157 then "Zhonya's Hourglass"
    when 3158 then "Ionian Boots of Lucidity"
    when 3159 then "Grez's Spectral Lantern"
    when 3165 then "Morellonomicon"
    when 3166 then "Bonetooth Necklace"
    when 3167 then "Bonetooth Necklace"
    when 3168 then "Bonetooth Necklace"
    when 3169 then "Bonetooth Necklace"
    when 3170 then "Moonflair Spellblade"
    when 3171 then "Bonetooth Necklace"
    when 3172 then "Zephyr"
    when 3174 then "Athene's Unholy Grail"
    when 3175 then "Head of Kha'Zix"
    when 3180 then "Odyn's Veil"
    when 3181 then "Sanguine Blade"
    when 3184 then "Entropy"
    when 3185 then "The Lightbringer"
    when 3186 then "Kitae's Bloodrazor"
    when 3187 then "Hextech Sweeper"
    when 3188 then "Blackfire Torch"
    when 3190 then "Locket of the Iron Solari"
    when 3191 then "Seeker's Armguard"
    when 3196 then "Augment: Power"
    when 3197 then "Augment: Gravity"
    when 3198 then "Augment: Death"
    when 3200 then "The Hex Core"
    when 3206 then "Spirit of the Spectral Wraith"
    when 3207 then "Spirit of the Ancient Golem"
    when 3209 then "Spirit of the Elder Lizard"
    when 3211 then "Spectre's Cowl"
    when 3222 then "Mikael's Crucible"
    when 3250 then "Enchantment: Homeguard"
    when 3251 then "Enchantment: Captain"
    when 3252 then "Enchantment: Furor"
    when 3253 then "Enchantment: Distortion"
    when 3254 then "Enchantment: Alacrity"
    when 3255 then "Enchantment: Homeguard"
    when 3256 then "Enchantment: Captain"
    when 3257 then "Enchantment: Furor"
    when 3258 then "Enchantment: Distortion"
    when 3259 then "Enchantment: Alacrity"
    when 3260 then "Enchantment: Homeguard"
    when 3261 then "Enchantment: Captain"
    when 3262 then "Enchantment: Furor"
    when 3263 then "Enchantment: Distortion"
    when 3264 then "Enchantment: Alacrity"
    when 3265 then "Enchantment: Homeguard"
    when 3266 then "Enchantment: Captain"
    when 3267 then "Enchantment: Furor"
    when 3268 then "Enchantment: Distortion"
    when 3269 then "Enchantment: Alacrity"
    when 3270 then "Enchantment: Homeguard"
    when 3271 then "Enchantment: Captain"
    when 3272 then "Enchantment: Furor"
    when 3273 then "Enchantment: Distortion"
    when 3274 then "Enchantment: Alacrity"
    when 3275 then "Enchantment: Homeguard"
    when 3276 then "Enchantment: Captain"
    when 3277 then "Enchantment: Furor"
    when 3278 then "Enchantment: Distortion"
    when 3279 then "Enchantment: Alacrity"
    when 3280 then "Enchantment: Homeguard"
    when 3281 then "Enchantment: Captain"
    when 3282 then "Enchantment: Furor"
    when 3283 then "Enchantment: Distortion"
    when 3284 then "Enchantment: Alacrity"
    when 3290 then "Twin Shadows"
    when 3301 then "Ancient Coin"
    when 3302 then "Relic Shield"
    when 3303 then "Spellthief's Edge"
    when 3340 then "Warding Totem (Trinket)"
    when 3341 then "Sweeping Lens (Trinket)"
    when 3342 then "Scrying Orb (Trinket)"
    when 3350 then "Greater Totem (Trinket)"
    when 3351 then "Greater Lens (Trinket)"
    when 3352 then "Greater Orb (Trinket)"
    when 3361 then "Greater Stealth Totem (Trinket)"
    when 3362 then "Greater Vision Totem (Trinket)"
    when 3363 then "Farsight Orb (Trinket)"
    when 3364 then "Oracle's Lens (Trinket)"
    when 3401 then "Face of the Mountain"
    end
  end

end
